manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: AntonyViridi
      url-base: https://github.com/AntonyViridi
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: viridikeyboard
      remote: AntonyViridi
      revision: main
  self:
    path: config
